# Generated by Django 5.2.14 on 2026-05-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_new_fields_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
    ]
