# Generated by Django 5.2.14 on 2026-06-08 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_article_language_topic_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContentBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_before', models.TextField()),
                ('run_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_backups', to='core.article')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'run_id'], name='core_articl_article_d14e47_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_text', models.CharField(blank=True, max_length=200)),
                ('link_type', models.CharField(choices=[('auto_category', 'Auto: Same Category'), ('auto_keyword', 'Auto: Keyword Match'), ('manual', 'Manual: Editor Placed'), ('pillar', 'Pillar: Category Page Link')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_run', models.CharField(blank=True, max_length=100)),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_links', to='core.article')),
                ('target_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_links', to='core.article')),
            ],
            options={
                'indexes': [models.Index(fields=['source_article', 'is_active'], name='core_articl_source__aa2244_idx'), models.Index(fields=['target_article', 'is_active'], name='core_articl_target__4009a3_idx')],
                'unique_together': {('source_article', 'target_article')},
            },
        ),
    ]
